# Generated by Django 5.0 on 2023-12-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationalAffiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('org_type', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('identification', models.CharField(max_length=50)),
                ('period', models.CharField(max_length=100)),
            ],
        ),
    ]
