# Generated by Django 5.0 on 2023-12-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_training'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('published_on', models.DateField()),
                ('published_by', models.CharField(max_length=100)),
                ('external_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
