# Generated by Django 5.0 on 2023-12-21 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
            ],
        ),
    ]
