# Generated by Django 5.0 on 2023-12-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_languageskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_img', models.ImageField(blank=True, null=True, upload_to='ref_img/')),
                ('refrence_type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('organization_name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('contact_no', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
