# Generated by Django 5.0 on 2023-12-23 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracurricular',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
