# Generated by Django 5.0 on 2023-12-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0012_trainingsection_trainingsubsection_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="training",
            name="medium",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
