# Generated by Django 5.0 on 2023-12-26 05:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0013_training_medium"),
    ]

    operations = [
        migrations.RenameField(
            model_name="training",
            old_name="location",
            new_name="institutes_instructor",
        ),
        migrations.RenameField(
            model_name="training",
            old_name="organization",
            new_name="location_platform",
        ),
    ]
