# Generated by Django 5.0 on 2024-01-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0014_rename_location_training_institutes_instructor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="project_info",
            field=models.TextField(blank=True, null=True),
        ),
    ]
