# Generated by Django 5.0 on 2024-01-02 16:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0015_experience_project_info"),
    ]

    operations = [
        migrations.RenameField(
            model_name="experience",
            old_name="work_field",
            new_name="organization",
        ),
    ]
